### ISSUE TITLE
Error with MD variable for runKrasTrain (Example 4 in User Guide)

### ISSUE THREAD

**Issue by edelaserna** [DanuserLab/u-surface3D#5] opened 2022-02-01 06:47 UTC
Hi! I am trying to go through Example 4 in the User Guide to learn how to train my own SVM. I've been consistently running into the same error when running runKrasTrain.m:

> Cell 1:  Cell1
> The provided path is not the path to a Matlab variable
> Unrecognized function or variable 'MD'.
> 
> Error in clickOnProtrusions (line 96)
>     sanityCheck(MD);
> 
> Error in runKrasTrain (line 60)
> clickOnProtrusions(p)

For some reason, clickOnProtrusions is not recognizing the MD variable in my workspace - it keeps getting stuck on lines 90-96 of clickonProtrusions.m when it tries to load the MovieData object and then run sanityCheck(MD). When I type in MD in the command line, Matlab registers that MD exists. I've checked the directory path in the MD variable and made sure it matches what I inputted for the analysisDirectory variable in line 38 of runKrasTrain.m. 

I'm quite stumped on how to troubleshoot and would appreciate any insight! Thank you so much!

**Comment by DanuserLab** [comment] 2024-10-21 17:08
Thank you for reporting this issue.

We were unable to reproduce the error on our end. We recommend using the debugger to step through the code and identify where it’s breaking. If you have any further questions or need additional assistance, please feel free to reach out.

We will go ahead and close this issue for now.

Best regards.

**Closed as completed by DanuserLab** 2024-10-21 17:08 UTC
